# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 08:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import panapp.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=12)),
                ('pan', models.CharField(max_length=10)),
                ('image', models.FileField(upload_to=panapp.utils.get_upload_file_path)),
                ('extracted_name', models.CharField(blank=True, max_length=50, null=True)),
                ('extracted_dob', models.CharField(blank=True, max_length=12, null=True)),
                ('extracted_pan', models.CharField(blank=True, max_length=10, null=True)),
                ('feedback_name', models.CharField(blank=True, max_length=50, null=True)),
                ('feedback_dob', models.CharField(blank=True, max_length=12, null=True)),
                ('feedback_pan', models.CharField(blank=True, max_length=10, null=True)),
                ('is_verified_auto', models.BooleanField(default=False)),
                ('is_verified_agent', models.BooleanField(default=False)),
                ('is_invalid_auto', models.BooleanField(default=False)),
                ('is_invalid_agent', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panapp.Agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
