# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panapp', '0003_auto_20171028_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='is_invalid_agent',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='is_invalid_auto',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='is_verified_auto',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='pan',
        ),
    ]
