# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panapp', '0005_userdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='is_invalid_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_verified_auto',
            field=models.BooleanField(default=False),
        ),
    ]
