# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panapp', '0006_auto_20171028_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='error_msg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
